### ISSUE TITLE
Decrypting full game

### ISSUE THREAD

**Issue by 09williamsad** [hax0r31337/resleriana_tools#2]
Does the tool support the full game download or just the base apk?
I have been testing it with the few catalog.json files that the full download has, and it does not seem to account for the different files.

If not, then I can upload a full download of the game files.

**Comment by hax0r31337** [comment]
I provided an example of download and decrypt from the CDN, all you need to do is replace the asset version with an actual one [here](https://github.com/hax0r31337/resleriana_tools/blob/main/main/main.go#L14)

**Comment by hax0r31337** [comment]
Aktsk seems have extra encryption on it's AssetBundle, even it have a readable header, but the contents of the AB seems to be encrypted, i'm working on it
